YEAR_LIMIT = "2010" # Checking all repositories after 2010
DATE_INTERVAL = 10
ORDER = "desc"
ERROR_CODE_NOT_FOUND = 404
LIMIT_OF_COLLECTED_REPOS = 1000
LIMIT_OF_NO_OF_VALID_COMBO = 1000
TAG_SCRIPTS = "scripts"
MISSING_SCRIPTS = "missing script"